project_id = "xshbayvwwearpkndnsoz"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327
image_transformation = {enabled = true}

[auth]
enabled = true
port = 54328
site_url = "http://127.0.0.1:3000"

[edge_functions]
enabled = true
port = 54329

[functions.create-payment-intent]
verify_jwt = true

[functions.secure-download]
verify_jwt = false