// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xshbayvwwearpkndnsoz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhzaGJheXZ3d2VhcnBrbmRuc296Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5MjM3MzAsImV4cCI6MjA3MTQ5OTczMH0.qZ1TnmIZVf9XVPXJ_5c0Eoih-YncNma97op7-K7lbRQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});